### ISSUE TITLE
Labels in the wrong language

### ISSUE THREAD

**Issue by andyscanzio** [admin-ch/CovidCertificate-App-iOS#275]
Hi, it seems that even if I have the app in Italian, some labels are still shown in English 

![image](https://user-images.githubusercontent.com/48473898/146377596-6f63060d-5513-4058-bcbb-02843e9bf55f.jpeg)

**Comment by goebelUB** [comment]
That's by design. For any language other than English, the labels will be shown twice, in two languages (e.g. Italian + English, or German + English). If you look at your paper certificate, it is the same there.

The reason is that the certificate (especially the paper, which the app mirrors) it is designed to be readable and understandable by others who don't speak your language, e.g. at border crossings. (Yes, ideally everyone scans the QR code, but you still want to keep the scope broad.) After all, it is an official document, and if you look at your passport, chances are that it also includes English labels.

**Comment by goebelUB** [comment]
It's better to ask for clarification too often than too little :)
