### ISSUE TITLE
„Invalid certificate“ verifying EU certificate 

### ISSUE THREAD

**Issue by mopenmind** [admin-ch/CovidCertificate-App-iOS#96]
I successfully added an EU certificate but it appears invalid. 
![2F39E06D-771A-4334-9432-5580B7EAE9E6](https://user-images.githubusercontent.com/1443755/123088471-0e60c200-d426-11eb-9b58-4daf63a770b7.jpeg)

**Comment by mopenmind** [comment]
![Uploading 02493654-36A1-4670-8AA7-3574E6DC0588.jpeg…]()

**Comment by StephanKonig** [comment]
As far as I know, this function is yet to come in early July.

**Comment by goebelUB** [comment]
The certificates issued by Switzerland are technically interoperable with EU's Digital Covid Certificates (DCC). The COVID Certificates apps of Switzerland are technically able to read and verify DCCs of other countries, and other countries are technically able to read the codes on Swiss certificates.

The apps download the list of trusted public keys dynamically since v1.2. The reason that the signature verification still fails is that we don't yet have the other countries' public keys. There is an ongoing political process to be completed before Switzerland is allowed to sync public keys with the productive European Gateway.

**Comment by skylenet** [comment]
Seems like the political process has been completed and that we should have a green light now to accept and validate EU certificates: https://ec.europa.eu/info/files/commission-implementing-decision-eu-equivalence-covid-19-certificates-issued-switzerland_en

**Comment by skylenet** [comment]
I think we can close this issue. Just tested it with the current version that is available on the App Store:

Adding a EU cert to the "Covid cert" app and scanning one via the "Covid check" app is working right now 🎉

**Comment by Vlaaaaaaad** [comment]
Can confirm, EU cert validation now works for me too!

**Comment by mopenmind** [comment]
confirmed, this works now
